-- Oral Exam System — PostgreSQL 16 schema
-- Source of truth: REVIEW 1/Database_LLMOramExam.md (synced ERD_v1)
-- Applied automatically via docker-entrypoint-initdb.d on first volume create.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================================================
-- 1. IDENTITY & ACADEMIC STRUCTURE
-- =============================================================================

CREATE TABLE roles (
    role_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
    user_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    role_id         INT NOT NULL REFERENCES roles (role_id),
    username        VARCHAR(100) NOT NULL UNIQUE,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255),
    full_name       VARCHAR(255) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE semesters (
    semester_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semester_code   VARCHAR(50) NOT NULL UNIQUE,
    start_date      DATE NOT NULL,
    end_date        DATE NOT NULL,
    CONSTRAINT ck_semesters_dates CHECK (end_date >= start_date)
);

CREATE TABLE courses (
    course_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code  VARCHAR(50) NOT NULL UNIQUE,
    course_name  VARCHAR(255) NOT NULL
);

CREATE TABLE classes (
    class_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id      INT NOT NULL REFERENCES courses (course_id),
    semester_id    INT NOT NULL REFERENCES semesters (semester_id),
    instructor_id  UUID NOT NULL REFERENCES users (user_id),
    class_name     VARCHAR(100) NOT NULL,
    CONSTRAINT uq_classes_semester_name UNIQUE (semester_id, class_name)
);

-- N–N: Users (students) ↔ Classes  (ERD: contains)
CREATE TABLE class_enrollments (
    enrollment_id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    class_id       INT NOT NULL REFERENCES classes (class_id) ON DELETE CASCADE,
    student_id     UUID NOT NULL REFERENCES users (user_id),
    student_code   VARCHAR(50),
    enrolled_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status         VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uq_class_enrollments UNIQUE (class_id, student_id),
    CONSTRAINT ck_enrollment_status CHECK (status IN ('ACTIVE', 'DROPPED', 'COMPLETED'))
);

CREATE INDEX ix_class_enrollments_student ON class_enrollments (student_id);

-- =============================================================================
-- 2. QUESTION BANK & RUBRIC
-- =============================================================================

CREATE TABLE exam_structures (
    structure_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id               INT NOT NULL REFERENCES courses (course_id),
    structure_name          VARCHAR(255) NOT NULL,
    exam_mode               VARCHAR(20) NOT NULL DEFAULT 'FIXED',
    easy_count              INT NOT NULL DEFAULT 0,
    medium_count            INT NOT NULL DEFAULT 0,
    hard_count              INT NOT NULL DEFAULT 0,
    duration_minutes        INT NOT NULL,
    max_followups           INT,
    followup_timeout_sec    INT,
    CONSTRAINT ck_exam_structures_mode CHECK (exam_mode IN ('FIXED', 'ADAPTIVE')),
    CONSTRAINT ck_exam_structures_counts CHECK (
        easy_count >= 0 AND medium_count >= 0 AND hard_count >= 0
        AND (easy_count + medium_count + hard_count) > 0
    ),
    CONSTRAINT ck_exam_structures_duration CHECK (duration_minutes > 0),
    CONSTRAINT ck_exam_structures_adaptive CHECK (
        exam_mode = 'FIXED'
        OR (max_followups IS NOT NULL AND max_followups >= 0
            AND followup_timeout_sec IS NOT NULL AND followup_timeout_sec > 0)
    )
);

CREATE TABLE practice_questions (
    question_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id      INT NOT NULL REFERENCES courses (course_id),
    content        TEXT NOT NULL,
    difficulty     VARCHAR(20) NOT NULL,
    model_answer   TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_practice_questions_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD'))
);

CREATE TABLE exam_questions (
    question_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id      INT NOT NULL REFERENCES courses (course_id),
    content        TEXT NOT NULL,
    difficulty     VARCHAR(20) NOT NULL,
    model_answer   TEXT NOT NULL,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    approved_by    UUID REFERENCES users (user_id),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_exam_questions_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD'))
);

CREATE TABLE rubric_items (
    rubric_id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    practice_question_id     UUID REFERENCES practice_questions (question_id) ON DELETE CASCADE,
    exam_question_id         UUID REFERENCES exam_questions (question_id) ON DELETE CASCADE,
    criteria_description     TEXT NOT NULL,
    max_score                NUMERIC(4, 2) NOT NULL,
    CONSTRAINT ck_rubric_xor_question CHECK (
        (practice_question_id IS NOT NULL AND exam_question_id IS NULL)
        OR (practice_question_id IS NULL AND exam_question_id IS NOT NULL)
    ),
    CONSTRAINT ck_rubric_max_score CHECK (max_score > 0 AND max_score <= 10)
);

CREATE INDEX ix_rubric_practice ON rubric_items (practice_question_id);
CREATE INDEX ix_rubric_exam ON rubric_items (exam_question_id);

-- =============================================================================
-- 3. PRACTICE & MOCK EXAM
-- =============================================================================

CREATE TABLE practice_sessions (
    session_id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id  UUID NOT NULL REFERENCES users (user_id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_practice_sessions_student ON practice_sessions (student_id);

-- Circular FK with practice_followup_questions: add followup FK after both tables exist
CREATE TABLE practice_answers (
    answer_id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id              UUID NOT NULL REFERENCES practice_sessions (session_id) ON DELETE CASCADE,
    question_id             UUID NOT NULL REFERENCES practice_questions (question_id),
    followup_question_id    UUID,
    parent_answer_id        UUID REFERENCES practice_answers (answer_id),
    user_transcript         TEXT,
    ai_score                NUMERIC(5, 2),
    ai_feedback             TEXT,
    status                  VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_practice_answers_status CHECK (status IN ('PENDING', 'GRADED', 'FAILED'))
);

CREATE TABLE practice_followup_questions (
    followup_id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    practice_answer_id     UUID NOT NULL REFERENCES practice_answers (answer_id) ON DELETE CASCADE,
    practice_session_id    UUID NOT NULL REFERENCES practice_sessions (session_id) ON DELETE CASCADE,
    round_index            INT NOT NULL DEFAULT 1,
    question_text          TEXT NOT NULL,
    trigger_score          NUMERIC(5, 2),
    gap_summary            JSONB,
    model_version          VARCHAR(100),
    prompt_version         VARCHAR(100),
    status                 VARCHAR(20) NOT NULL DEFAULT 'GENERATED',
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_practice_followup_status CHECK (
        status IN ('GENERATED', 'ANSWERED', 'SKIPPED', 'FAILED')
    ),
    CONSTRAINT ck_practice_followup_round CHECK (round_index >= 1)
);

ALTER TABLE practice_answers
    ADD CONSTRAINT fk_practice_answers_followup
    FOREIGN KEY (followup_question_id)
    REFERENCES practice_followup_questions (followup_id);

CREATE INDEX ix_practice_answers_session ON practice_answers (session_id);

-- Quota: Users N–N Courses (per day)
CREATE TABLE mock_exam_quotas (
    quota_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id   UUID NOT NULL REFERENCES users (user_id),
    course_id    INT NOT NULL REFERENCES courses (course_id),
    quota_date   DATE NOT NULL DEFAULT (CURRENT_DATE),
    used_count   INT NOT NULL DEFAULT 0,
    max_count    INT NOT NULL DEFAULT 3,
    CONSTRAINT uq_mock_exam_quotas UNIQUE (student_id, course_id, quota_date),
    CONSTRAINT ck_mock_quota_counts CHECK (used_count >= 0 AND max_count > 0 AND used_count <= max_count)
);

CREATE TABLE mock_exam_sessions (
    mock_session_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id         UUID NOT NULL REFERENCES users (user_id),
    structure_id       INT NOT NULL REFERENCES exam_structures (structure_id),
    exam_mode          VARCHAR(20) NOT NULL DEFAULT 'FIXED',
    overall_score      NUMERIC(5, 2),
    overall_feedback   TEXT,
    status             VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    started_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at       TIMESTAMPTZ,
    CONSTRAINT ck_mock_sessions_mode CHECK (exam_mode IN ('FIXED', 'ADAPTIVE')),
    CONSTRAINT ck_mock_sessions_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);

CREATE INDEX ix_mock_sessions_student ON mock_exam_sessions (student_id);

CREATE TABLE mock_exam_answers (
    mock_answer_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mock_session_id         UUID NOT NULL REFERENCES mock_exam_sessions (mock_session_id) ON DELETE CASCADE,
    question_id             UUID NOT NULL REFERENCES practice_questions (question_id),
    followup_question_id    UUID,
    parent_answer_id        UUID REFERENCES mock_exam_answers (mock_answer_id),
    round_index             INT NOT NULL DEFAULT 0,
    user_transcript         TEXT,
    ai_score                NUMERIC(5, 2),
    ai_feedback             TEXT,
    status                  VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT ck_mock_answers_status CHECK (status IN ('PENDING', 'GRADED', 'FAILED')),
    CONSTRAINT ck_mock_answers_round CHECK (round_index >= 0)
);

CREATE TABLE mock_exam_followup_questions (
    followup_id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mock_answer_id                  UUID NOT NULL REFERENCES mock_exam_answers (mock_answer_id) ON DELETE CASCADE,
    mock_session_id                 UUID NOT NULL REFERENCES mock_exam_sessions (mock_session_id) ON DELETE CASCADE,
    round_index                     INT NOT NULL DEFAULT 1,
    question_text                   TEXT NOT NULL,
    context_transcript              TEXT,
    parent_practice_question_id     UUID REFERENCES practice_questions (question_id),
    model_version                   VARCHAR(100),
    prompt_version                  VARCHAR(100),
    status                          VARCHAR(30) NOT NULL DEFAULT 'GENERATED',
    timeout_sec                     INT,
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_mock_followup_status CHECK (
        status IN ('GENERATED', 'ANSWERED', 'SKIPPED_TIMEOUT', 'FAILED')
    ),
    CONSTRAINT ck_mock_followup_round CHECK (round_index >= 1)
);

ALTER TABLE mock_exam_answers
    ADD CONSTRAINT fk_mock_answers_followup
    FOREIGN KEY (followup_question_id)
    REFERENCES mock_exam_followup_questions (followup_id);

CREATE INDEX ix_mock_answers_session ON mock_exam_answers (mock_session_id);

-- =============================================================================
-- 4. REAL / OFFICIAL LAB EXAM
-- =============================================================================

CREATE TABLE real_exam_sessions (
    exam_session_id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    class_id         INT NOT NULL REFERENCES classes (class_id),
    structure_id     INT NOT NULL REFERENCES exam_structures (structure_id),
    exam_mode        VARCHAR(20) NOT NULL DEFAULT 'FIXED',
    title            VARCHAR(255) NOT NULL,
    exam_date        DATE NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_real_sessions_mode CHECK (exam_mode IN ('FIXED', 'ADAPTIVE'))
);

CREATE TABLE real_exam_session_shifts (
    shift_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    exam_session_id   UUID NOT NULL REFERENCES real_exam_sessions (exam_session_id) ON DELETE CASCADE,
    shift_name        VARCHAR(100) NOT NULL,
    start_time        TIMESTAMPTZ NOT NULL,
    end_time          TIMESTAMPTZ NOT NULL,
    lab_room          VARCHAR(100) NOT NULL,
    CONSTRAINT ck_shift_times CHECK (end_time > start_time)
);

-- N–N: Students ↔ Shifts
CREATE TABLE real_exam_assignments (
    assignment_id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shift_id            UUID NOT NULL REFERENCES real_exam_session_shifts (shift_id) ON DELETE CASCADE,
    student_id          UUID NOT NULL REFERENCES users (user_id),
    booth_number        INT,
    attendance_status   VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED',
    CONSTRAINT uq_real_exam_assignments UNIQUE (shift_id, student_id),
    CONSTRAINT ck_attendance_status CHECK (
        attendance_status IN ('NOT_STARTED', 'ATTENDED', 'ABSENT')
    )
);

CREATE TABLE real_exam_results (
    result_id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    assignment_id        UUID NOT NULL UNIQUE REFERENCES real_exam_assignments (assignment_id),
    status               VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    mic_check_passed     BOOLEAN NOT NULL DEFAULT FALSE,
    violation_count      INT NOT NULL DEFAULT 0,
    is_flagged           BOOLEAN NOT NULL DEFAULT FALSE,
    ai_score             NUMERIC(5, 2),
    final_score          NUMERIC(5, 2),
    reviewed_by          UUID REFERENCES users (user_id),
    reviewed_at          TIMESTAMPTZ,
    is_overridden        BOOLEAN NOT NULL DEFAULT FALSE,
    override_reason      TEXT,
    is_locked            BOOLEAN NOT NULL DEFAULT FALSE,
    sha256_hash          VARCHAR(128),
    submitted_at         TIMESTAMPTZ,
    locked_at            TIMESTAMPTZ,
    CONSTRAINT ck_real_results_status CHECK (
        status IN (
            'NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED',
            'TRANSCRIBED', 'AI_GRADED', 'LOCKED'
        )
    ),
    CONSTRAINT ck_real_results_violations CHECK (violation_count >= 0),
    CONSTRAINT ck_real_results_override CHECK (
        is_overridden = FALSE OR (override_reason IS NOT NULL AND length(trim(override_reason)) > 0)
    )
);

CREATE TABLE real_exam_answers (
    real_answer_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    result_id               UUID NOT NULL REFERENCES real_exam_results (result_id) ON DELETE CASCADE,
    question_id             UUID NOT NULL REFERENCES exam_questions (question_id),
    followup_question_id    UUID,
    parent_answer_id        UUID REFERENCES real_exam_answers (real_answer_id),
    round_index             INT NOT NULL DEFAULT 0,
    audio_url               TEXT,
    transcript              TEXT,
    timestamps_json         JSONB,
    rubric_snapshot         JSONB,
    ai_evidence             TEXT,
    ai_score                NUMERIC(5, 2),
    final_score             NUMERIC(5, 2),
    CONSTRAINT ck_real_answers_round CHECK (round_index >= 0)
);

CREATE TABLE real_exam_followup_questions (
    followup_id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    real_answer_id         UUID NOT NULL REFERENCES real_exam_answers (real_answer_id) ON DELETE CASCADE,
    result_id              UUID NOT NULL REFERENCES real_exam_results (result_id) ON DELETE CASCADE,
    round_index            INT NOT NULL DEFAULT 1,
    question_text          TEXT NOT NULL,
    context_transcript     TEXT,
    prompt_snapshot        TEXT NOT NULL,
    model_version          VARCHAR(100),
    prompt_version         VARCHAR(100),
    status                 VARCHAR(30) NOT NULL DEFAULT 'GENERATED',
    timeout_sec            INT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_real_followup_status CHECK (
        status IN ('GENERATED', 'ANSWERED', 'SKIPPED_TIMEOUT', 'FAILED')
    ),
    CONSTRAINT ck_real_followup_round CHECK (round_index >= 1)
);

ALTER TABLE real_exam_answers
    ADD CONSTRAINT fk_real_answers_followup
    FOREIGN KEY (followup_question_id)
    REFERENCES real_exam_followup_questions (followup_id);

CREATE INDEX ix_real_answers_result ON real_exam_answers (result_id);

CREATE TABLE audit_logs (
    log_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        UUID NOT NULL REFERENCES users (user_id),
    action         VARCHAR(100) NOT NULL,
    target_table   VARCHAR(100) NOT NULL,
    target_id      UUID,
    old_values     JSONB,
    new_values     JSONB,
    ip_address     VARCHAR(64),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_audit_logs_user ON audit_logs (user_id);
CREATE INDEX ix_audit_logs_target ON audit_logs (target_table, target_id);
CREATE INDEX ix_audit_logs_created ON audit_logs (created_at DESC);
