// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OralExamination.Infrastructure.Persistence;

#nullable disable

namespace OralExamination.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OralExamDbContext))]
    [Migration("20260929093646_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OralExamination.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_table");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LogId")
                        .HasName("audit_logs_pkey");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_audit_logs_created")
                        .IsDescending();

                    b.HasIndex(new[] { "TargetTable", "TargetId" }, "ix_audit_logs_target");

                    b.HasIndex(new[] { "UserId" }, "ix_audit_logs_user");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("class_name");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uuid")
                        .HasColumnName("instructor_id");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer")
                        .HasColumnName("semester_id");

                    b.HasKey("ClassId")
                        .HasName("classes_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex(new[] { "SemesterId", "ClassName" }, "uq_classes_semester_name")
                        .IsUnique();

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.ClassEnrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'ACTIVE'::character varying");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_code");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("EnrollmentId")
                        .HasName("class_enrollments_pkey");

                    b.HasIndex(new[] { "StudentId" }, "ix_class_enrollments_student");

                    b.HasIndex(new[] { "ClassId", "StudentId" }, "uq_class_enrollments")
                        .IsUnique();

                    b.ToTable("class_enrollments", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("course_code");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("course_name");

                    b.HasKey("CourseId")
                        .HasName("courses_pkey");

                    b.HasIndex(new[] { "CourseCode" }, "courses_course_code_key")
                        .IsUnique();

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.ExamQuestion", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("question_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ModelAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_answer");

                    b.HasKey("QuestionId")
                        .HasName("exam_questions_pkey");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CourseId");

                    b.ToTable("exam_questions", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.ExamStructure", b =>
                {
                    b.Property<int>("StructureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("structure_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StructureId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<int>("EasyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("easy_count");

                    b.Property<string>("ExamMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("exam_mode")
                        .HasDefaultValueSql("'FIXED'::character varying");

                    b.Property<int?>("FollowupTimeoutSec")
                        .HasColumnType("integer")
                        .HasColumnName("followup_timeout_sec");

                    b.Property<int>("HardCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("hard_count");

                    b.Property<int?>("MaxFollowups")
                        .HasColumnType("integer")
                        .HasColumnName("max_followups");

                    b.Property<int>("MediumCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("medium_count");

                    b.Property<string>("StructureName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("structure_name");

                    b.HasKey("StructureId")
                        .HasName("exam_structures_pkey");

                    b.HasIndex("CourseId");

                    b.ToTable("exam_structures", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.MockExamAnswer", b =>
                {
                    b.Property<Guid>("MockAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("mock_answer_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiFeedback")
                        .HasColumnType("text")
                        .HasColumnName("ai_feedback");

                    b.Property<decimal?>("AiScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ai_score");

                    b.Property<Guid?>("FollowupQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("followup_question_id");

                    b.Property<Guid>("MockSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mock_session_id");

                    b.Property<Guid?>("ParentAnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_answer_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("RoundIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("round_index");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'::character varying");

                    b.Property<string>("UserTranscript")
                        .HasColumnType("text")
                        .HasColumnName("user_transcript");

                    b.HasKey("MockAnswerId")
                        .HasName("mock_exam_answers_pkey");

                    b.HasIndex("FollowupQuestionId");

                    b.HasIndex("ParentAnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex(new[] { "MockSessionId" }, "ix_mock_answers_session");

                    b.ToTable("mock_exam_answers", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.MockExamFollowupQuestion", b =>
                {
                    b.Property<Guid>("FollowupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("followup_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContextTranscript")
                        .HasColumnType("text")
                        .HasColumnName("context_transcript");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MockAnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("mock_answer_id");

                    b.Property<Guid>("MockSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mock_session_id");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_version");

                    b.Property<Guid?>("ParentPracticeQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_practice_question_id");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<int>("RoundIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("round_index");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'GENERATED'::character varying");

                    b.Property<int?>("TimeoutSec")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_sec");

                    b.HasKey("FollowupId")
                        .HasName("mock_exam_followup_questions_pkey");

                    b.HasIndex("MockAnswerId");

                    b.HasIndex("MockSessionId");

                    b.HasIndex("ParentPracticeQuestionId");

                    b.ToTable("mock_exam_followup_questions", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.MockExamQuota", b =>
                {
                    b.Property<Guid>("QuotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("quota_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("MaxCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_count");

                    b.Property<DateOnly>("QuotaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("quota_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("used_count");

                    b.HasKey("QuotaId")
                        .HasName("mock_exam_quotas_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex(new[] { "StudentId", "CourseId", "QuotaDate" }, "uq_mock_exam_quotas")
                        .IsUnique();

                    b.ToTable("mock_exam_quotas", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.MockExamSession", b =>
                {
                    b.Property<Guid>("MockSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("mock_session_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ExamMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("exam_mode")
                        .HasDefaultValueSql("'FIXED'::character varying");

                    b.Property<string>("OverallFeedback")
                        .HasColumnType("text")
                        .HasColumnName("overall_feedback");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overall_score");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'IN_PROGRESS'::character varying");

                    b.Property<int>("StructureId")
                        .HasColumnType("integer")
                        .HasColumnName("structure_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("MockSessionId")
                        .HasName("mock_exam_sessions_pkey");

                    b.HasIndex("StructureId");

                    b.HasIndex(new[] { "StudentId" }, "ix_mock_sessions_student");

                    b.ToTable("mock_exam_sessions", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.PracticeAnswer", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("answer_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiFeedback")
                        .HasColumnType("text")
                        .HasColumnName("ai_feedback");

                    b.Property<decimal?>("AiScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ai_score");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("FollowupQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("followup_question_id");

                    b.Property<Guid?>("ParentAnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_answer_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'::character varying");

                    b.Property<string>("UserTranscript")
                        .HasColumnType("text")
                        .HasColumnName("user_transcript");

                    b.HasKey("AnswerId")
                        .HasName("practice_answers_pkey");

                    b.HasIndex("FollowupQuestionId");

                    b.HasIndex("ParentAnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex(new[] { "SessionId" }, "ix_practice_answers_session");

                    b.ToTable("practice_answers", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.PracticeFollowupQuestion", b =>
                {
                    b.Property<Guid>("FollowupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("followup_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GapSummary")
                        .HasColumnType("jsonb")
                        .HasColumnName("gap_summary");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_version");

                    b.Property<Guid>("PracticeAnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_answer_id");

                    b.Property<Guid>("PracticeSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_session_id");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<int>("RoundIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("round_index");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'GENERATED'::character varying");

                    b.Property<decimal?>("TriggerScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("trigger_score");

                    b.HasKey("FollowupId")
                        .HasName("practice_followup_questions_pkey");

                    b.HasIndex("PracticeAnswerId");

                    b.HasIndex("PracticeSessionId");

                    b.ToTable("practice_followup_questions", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.PracticeQuestion", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("question_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("ModelAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_answer");

                    b.HasKey("QuestionId")
                        .HasName("practice_questions_pkey");

                    b.HasIndex("CourseId");

                    b.ToTable("practice_questions", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.PracticeSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("SessionId")
                        .HasName("practice_sessions_pkey");

                    b.HasIndex(new[] { "StudentId" }, "ix_practice_sessions_student");

                    b.ToTable("practice_sessions", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamAnswer", b =>
                {
                    b.Property<Guid>("RealAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("real_answer_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiEvidence")
                        .HasColumnType("text")
                        .HasColumnName("ai_evidence");

                    b.Property<decimal?>("AiScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ai_score");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text")
                        .HasColumnName("audio_url");

                    b.Property<decimal?>("FinalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("final_score");

                    b.Property<Guid?>("FollowupQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("followup_question_id");

                    b.Property<Guid?>("ParentAnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_answer_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_id");

                    b.Property<int>("RoundIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("round_index");

                    b.Property<string>("RubricSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("rubric_snapshot");

                    b.Property<string>("TimestampsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("timestamps_json");

                    b.Property<string>("Transcript")
                        .HasColumnType("text")
                        .HasColumnName("transcript");

                    b.HasKey("RealAnswerId")
                        .HasName("real_exam_answers_pkey");

                    b.HasIndex("FollowupQuestionId");

                    b.HasIndex("ParentAnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex(new[] { "ResultId" }, "ix_real_answers_result");

                    b.ToTable("real_exam_answers", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("attendance_status")
                        .HasDefaultValueSql("'NOT_STARTED'::character varying");

                    b.Property<int?>("BoothNumber")
                        .HasColumnType("integer")
                        .HasColumnName("booth_number");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("AssignmentId")
                        .HasName("real_exam_assignments_pkey");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "ShiftId", "StudentId" }, "uq_real_exam_assignments")
                        .IsUnique();

                    b.ToTable("real_exam_assignments", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamFollowupQuestion", b =>
                {
                    b.Property<Guid>("FollowupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("followup_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContextTranscript")
                        .HasColumnType("text")
                        .HasColumnName("context_transcript");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_version");

                    b.Property<string>("PromptSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_snapshot");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<Guid>("RealAnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("real_answer_id");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_id");

                    b.Property<int>("RoundIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("round_index");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'GENERATED'::character varying");

                    b.Property<int?>("TimeoutSec")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_sec");

                    b.HasKey("FollowupId")
                        .HasName("real_exam_followup_questions_pkey");

                    b.HasIndex("RealAnswerId");

                    b.HasIndex("ResultId");

                    b.ToTable("real_exam_followup_questions", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamResult", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("result_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("AiScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ai_score");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<decimal?>("FinalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("final_score");

                    b.Property<bool>("IsFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_flagged");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<bool>("IsOverridden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_overridden");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<bool>("MicCheckPassed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("mic_check_passed");

                    b.Property<string>("OverrideReason")
                        .HasColumnType("text")
                        .HasColumnName("override_reason");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Sha256Hash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sha256_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'NOT_STARTED'::character varying");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("ViolationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("violation_count");

                    b.HasKey("ResultId")
                        .HasName("real_exam_results_pkey");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex(new[] { "AssignmentId" }, "real_exam_results_assignment_id_key")
                        .IsUnique();

                    b.ToTable("real_exam_results", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamSession", b =>
                {
                    b.Property<Guid>("ExamSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exam_session_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date")
                        .HasColumnName("exam_date");

                    b.Property<string>("ExamMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("exam_mode")
                        .HasDefaultValueSql("'FIXED'::character varying");

                    b.Property<int>("StructureId")
                        .HasColumnType("integer")
                        .HasColumnName("structure_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("ExamSessionId")
                        .HasName("real_exam_sessions_pkey");

                    b.HasIndex("ClassId");

                    b.HasIndex("StructureId");

                    b.ToTable("real_exam_sessions", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamSessionShift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("ExamSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_session_id");

                    b.Property<string>("LabRoom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lab_room");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shift_name");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("ShiftId")
                        .HasName("real_exam_session_shifts_pkey");

                    b.HasIndex("ExamSessionId");

                    b.ToTable("real_exam_session_shifts", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "RoleName" }, "roles_role_name_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RubricItem", b =>
                {
                    b.Property<Guid>("RubricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rubric_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CriteriaDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("criteria_description");

                    b.Property<Guid?>("ExamQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_question_id");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("max_score");

                    b.Property<Guid?>("PracticeQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_question_id");

                    b.HasKey("RubricId")
                        .HasName("rubric_items_pkey");

                    b.HasIndex(new[] { "ExamQuestionId" }, "ix_rubric_exam");

                    b.HasIndex(new[] { "PracticeQuestionId" }, "ix_rubric_practice");

                    b.ToTable("rubric_items", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("semester_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SemesterId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("SemesterCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("semester_code");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("SemesterId")
                        .HasName("semesters_pkey");

                    b.HasIndex(new[] { "SemesterCode" }, "semesters_semester_code_key")
                        .IsUnique();

                    b.ToTable("semesters", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("audit_logs_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.Class", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("classes_course_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.User", "Instructor")
                        .WithMany("Classes")
                        .HasForeignKey("InstructorId")
                        .IsRequired()
                        .HasConstraintName("classes_instructor_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.Semester", "Semester")
                        .WithMany("Classes")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("classes_semester_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.ClassEnrollment", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.Class", "Class")
                        .WithMany("ClassEnrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("class_enrollments_class_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.User", "Student")
                        .WithMany("ClassEnrollments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("class_enrollments_student_id_fkey");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.ExamQuestion", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.User", "ApprovedByNavigation")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("exam_questions_approved_by_fkey");

                    b.HasOne("OralExamination.Domain.Entities.Course", "Course")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("exam_questions_course_id_fkey");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.ExamStructure", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.Course", "Course")
                        .WithMany("ExamStructures")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("exam_structures_course_id_fkey");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.MockExamAnswer", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.MockExamFollowupQuestion", "FollowupQuestion")
                        .WithMany("MockExamAnswers")
                        .HasForeignKey("FollowupQuestionId")
                        .HasConstraintName("fk_mock_answers_followup");

                    b.HasOne("OralExamination.Domain.Entities.MockExamSession", "MockSession")
                        .WithMany("MockExamAnswers")
                        .HasForeignKey("MockSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("mock_exam_answers_mock_session_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.MockExamAnswer", "ParentAnswer")
                        .WithMany("InverseParentAnswer")
                        .HasForeignKey("ParentAnswerId")
                        .HasConstraintName("mock_exam_answers_parent_answer_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.PracticeQuestion", "Question")
                        .WithMany("MockExamAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("mock_exam_answers_question_id_fkey");

                    b.Navigation("FollowupQuestion");

                    b.Navigation("MockSession");

                    b.Navigation("ParentAnswer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.MockExamFollowupQuestion", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.MockExamAnswer", "MockAnswer")
                        .WithMany("MockExamFollowupQuestions")
                        .HasForeignKey("MockAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("mock_exam_followup_questions_mock_answer_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.MockExamSession", "MockSession")
                        .WithMany("MockExamFollowupQuestions")
                        .HasForeignKey("MockSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("mock_exam_followup_questions_mock_session_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.PracticeQuestion", "ParentPracticeQuestion")
                        .WithMany("MockExamFollowupQuestions")
                        .HasForeignKey("ParentPracticeQuestionId")
                        .HasConstraintName("mock_exam_followup_questions_parent_practice_question_id_fkey");

                    b.Navigation("MockAnswer");

                    b.Navigation("MockSession");

                    b.Navigation("ParentPracticeQuestion");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.MockExamQuota", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.Course", "Course")
                        .WithMany("MockExamQuota")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("mock_exam_quotas_course_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.User", "Student")
                        .WithMany("MockExamQuota")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("mock_exam_quotas_student_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.MockExamSession", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.ExamStructure", "Structure")
                        .WithMany("MockExamSessions")
                        .HasForeignKey("StructureId")
                        .IsRequired()
                        .HasConstraintName("mock_exam_sessions_structure_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.User", "Student")
                        .WithMany("MockExamSessions")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("mock_exam_sessions_student_id_fkey");

                    b.Navigation("Structure");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.PracticeAnswer", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.PracticeFollowupQuestion", "FollowupQuestion")
                        .WithMany("PracticeAnswers")
                        .HasForeignKey("FollowupQuestionId")
                        .HasConstraintName("fk_practice_answers_followup");

                    b.HasOne("OralExamination.Domain.Entities.PracticeAnswer", "ParentAnswer")
                        .WithMany("InverseParentAnswer")
                        .HasForeignKey("ParentAnswerId")
                        .HasConstraintName("practice_answers_parent_answer_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.PracticeQuestion", "Question")
                        .WithMany("PracticeAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("practice_answers_question_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.PracticeSession", "Session")
                        .WithMany("PracticeAnswers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("practice_answers_session_id_fkey");

                    b.Navigation("FollowupQuestion");

                    b.Navigation("ParentAnswer");

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.PracticeFollowupQuestion", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.PracticeAnswer", "PracticeAnswer")
                        .WithMany("PracticeFollowupQuestions")
                        .HasForeignKey("PracticeAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("practice_followup_questions_practice_answer_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.PracticeSession", "PracticeSession")
                        .WithMany("PracticeFollowupQuestions")
                        .HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("practice_followup_questions_practice_session_id_fkey");

                    b.Navigation("PracticeAnswer");

                    b.Navigation("PracticeSession");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.PracticeQuestion", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.Course", "Course")
                        .WithMany("PracticeQuestions")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("practice_questions_course_id_fkey");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.PracticeSession", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.User", "Student")
                        .WithMany("PracticeSessions")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("practice_sessions_student_id_fkey");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamAnswer", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.RealExamFollowupQuestion", "FollowupQuestion")
                        .WithMany("RealExamAnswers")
                        .HasForeignKey("FollowupQuestionId")
                        .HasConstraintName("fk_real_answers_followup");

                    b.HasOne("OralExamination.Domain.Entities.RealExamAnswer", "ParentAnswer")
                        .WithMany("InverseParentAnswer")
                        .HasForeignKey("ParentAnswerId")
                        .HasConstraintName("real_exam_answers_parent_answer_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.ExamQuestion", "Question")
                        .WithMany("RealExamAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("real_exam_answers_question_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.RealExamResult", "Result")
                        .WithMany("RealExamAnswers")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("real_exam_answers_result_id_fkey");

                    b.Navigation("FollowupQuestion");

                    b.Navigation("ParentAnswer");

                    b.Navigation("Question");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamAssignment", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.RealExamSessionShift", "Shift")
                        .WithMany("RealExamAssignments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("real_exam_assignments_shift_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.User", "Student")
                        .WithMany("RealExamAssignments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("real_exam_assignments_student_id_fkey");

                    b.Navigation("Shift");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamFollowupQuestion", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.RealExamAnswer", "RealAnswer")
                        .WithMany("RealExamFollowupQuestions")
                        .HasForeignKey("RealAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("real_exam_followup_questions_real_answer_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.RealExamResult", "Result")
                        .WithMany("RealExamFollowupQuestions")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("real_exam_followup_questions_result_id_fkey");

                    b.Navigation("RealAnswer");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamResult", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.RealExamAssignment", "Assignment")
                        .WithOne("RealExamResult")
                        .HasForeignKey("OralExamination.Domain.Entities.RealExamResult", "AssignmentId")
                        .IsRequired()
                        .HasConstraintName("real_exam_results_assignment_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.User", "ReviewedByNavigation")
                        .WithMany("RealExamResults")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("real_exam_results_reviewed_by_fkey");

                    b.Navigation("Assignment");

                    b.Navigation("ReviewedByNavigation");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamSession", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.Class", "Class")
                        .WithMany("RealExamSessions")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("real_exam_sessions_class_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.ExamStructure", "Structure")
                        .WithMany("RealExamSessions")
                        .HasForeignKey("StructureId")
                        .IsRequired()
                        .HasConstraintName("real_exam_sessions_structure_id_fkey");

                    b.Navigation("Class");

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamSessionShift", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.RealExamSession", "ExamSession")
                        .WithMany("RealExamSessionShifts")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("real_exam_session_shifts_exam_session_id_fkey");

                    b.Navigation("ExamSession");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RubricItem", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.ExamQuestion", "ExamQuestion")
                        .WithMany("RubricItems")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("rubric_items_exam_question_id_fkey");

                    b.HasOne("OralExamination.Domain.Entities.PracticeQuestion", "PracticeQuestion")
                        .WithMany("RubricItems")
                        .HasForeignKey("PracticeQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("rubric_items_practice_question_id_fkey");

                    b.Navigation("ExamQuestion");

                    b.Navigation("PracticeQuestion");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.User", b =>
                {
                    b.HasOne("OralExamination.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("users_role_id_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.Class", b =>
                {
                    b.Navigation("ClassEnrollments");

                    b.Navigation("RealExamSessions");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.Course", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("ExamQuestions");

                    b.Navigation("ExamStructures");

                    b.Navigation("MockExamQuota");

                    b.Navigation("PracticeQuestions");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.ExamQuestion", b =>
                {
                    b.Navigation("RealExamAnswers");

                    b.Navigation("RubricItems");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.ExamStructure", b =>
                {
                    b.Navigation("MockExamSessions");

                    b.Navigation("RealExamSessions");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.MockExamAnswer", b =>
                {
                    b.Navigation("InverseParentAnswer");

                    b.Navigation("MockExamFollowupQuestions");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.MockExamFollowupQuestion", b =>
                {
                    b.Navigation("MockExamAnswers");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.MockExamSession", b =>
                {
                    b.Navigation("MockExamAnswers");

                    b.Navigation("MockExamFollowupQuestions");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.PracticeAnswer", b =>
                {
                    b.Navigation("InverseParentAnswer");

                    b.Navigation("PracticeFollowupQuestions");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.PracticeFollowupQuestion", b =>
                {
                    b.Navigation("PracticeAnswers");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.PracticeQuestion", b =>
                {
                    b.Navigation("MockExamAnswers");

                    b.Navigation("MockExamFollowupQuestions");

                    b.Navigation("PracticeAnswers");

                    b.Navigation("RubricItems");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.PracticeSession", b =>
                {
                    b.Navigation("PracticeAnswers");

                    b.Navigation("PracticeFollowupQuestions");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamAnswer", b =>
                {
                    b.Navigation("InverseParentAnswer");

                    b.Navigation("RealExamFollowupQuestions");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamAssignment", b =>
                {
                    b.Navigation("RealExamResult");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamFollowupQuestion", b =>
                {
                    b.Navigation("RealExamAnswers");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamResult", b =>
                {
                    b.Navigation("RealExamAnswers");

                    b.Navigation("RealExamFollowupQuestions");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamSession", b =>
                {
                    b.Navigation("RealExamSessionShifts");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.RealExamSessionShift", b =>
                {
                    b.Navigation("RealExamAssignments");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.Semester", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("OralExamination.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ClassEnrollments");

                    b.Navigation("Classes");

                    b.Navigation("ExamQuestions");

                    b.Navigation("MockExamQuota");

                    b.Navigation("MockExamSessions");

                    b.Navigation("PracticeSessions");

                    b.Navigation("RealExamAssignments");

                    b.Navigation("RealExamResults");
                });
#pragma warning restore 612, 618
        }
    }
}
